/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutricionista.vistas;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import nutricionista.accesodatos.ComidaData;
import nutricionista.accesodatos.DietaData;
import nutricionista.accesodatos.PacienteData;
import nutricionista.entidades.Comida;
import nutricionista.entidades.Dieta;
import nutricionista.entidades.Paciente;

/**
 *
 * @author Jorge Santiago
 */
public class BusquedaXPeso extends javax.swing.JInternalFrame {

    private Connection con = null;

    private Dieta dieta;
    private Comida comida;
    private Paciente pacienteactual;

    private List<Comida> comidas;
    private List<Dieta> PacxP;
    private ComidaData cData;
    private DietaData DData;
    private PacienteData pacData;

    private DefaultTableModel tabla = new DefaultTableModel();

    /**
     * Creates new form BusquedaXPeso
     */
    public BusquedaXPeso() {
        initComponents();
        dieta = new Dieta();
        comida = new Comida();
        Paciente pac = new Paciente();
        cData = new ComidaData();
        DData = new DietaData();
        pacData = new PacienteData();
        List<Paciente> ArrayList = null;
        List<Paciente> Paciente = null;
        PacxP = (ArrayList<Dieta>) pacData.ListaPacientesxPeso();
        Paciente = (ArrayList<Paciente>) pacData.ListaPacientesxPeso2();

        armarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPacientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buqueda de Paciente por Peso");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Busqueda de Paciente por Peso");

        jTPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTPacientes);

        jLabel2.setText("No Cumplieron Objetivo");

        jBuscar.setText("Buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jBuscar)
                        .addGap(42, 42, 42)
                        .addComponent(jButton1))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBuscar)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        try {
            //Double pesoFinal=Double.parseDouble(jTInicial.getText());
            //int pesofin= Integer.parseInt(jTFinal.getText());

            //Paciente pacienteactual= pacData.buscarPacientexPeso(pesoFinal);
            //pacienteactual=pacData.buscarPacientexPeso(pesofin, pesoini);
//        Paciente paciente=null;
//       
//        List <Paciente> pacientes= (ArrayList) pacData.ListaPacientesxPeso(pesoFinal);
//       
//        for (Paciente p: pacientes){
//        tabla.addRow(new Object[] { p.getId_paciente(), p.getNombre(), p.getApellido(), dieta.getPesoInicio(),dieta.getPesoFinal() });
//        }
//         Materia selec= (Materia)jCMaterias.getSelectedItem();
            List<Paciente> Paciente = (ArrayList) pacData.ListaPacientesxPeso2();

            List<Dieta> PacxP = (ArrayList) pacData.ListaPacientesxPeso();

            for (Dieta dieta : PacxP) {
                Paciente paciente=pacData.buscarPacienteID(dieta.getId_paciente());
                tabla.addRow(new Object[]{dieta.getId_paciente(),paciente.getNombre(), paciente.getApellido(), dieta.getPesoInicio(), dieta.getPesoFinal()});
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un peso Valido");
        }

    }//GEN-LAST:event_jBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        borrarFilasTablas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void armarTabla() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID_PACIENTE");
        filaCabecera.add("NOMBRE");
        filaCabecera.add("APELLIDO");
        filaCabecera.add("PESO INICIAL");
        filaCabecera.add("PESO FINAL");
        for (Object it : filaCabecera) {
            tabla.addColumn(it);

        }
        jTPacientes.setModel(tabla);

    }

    private void borrarFilasTablas() {
        int indice = tabla.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {
            tabla.removeRow(i);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTPacientes;
    // End of variables declaration//GEN-END:variables
}
