/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutricionista.vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import nutricionista.accesodatos.ComidaData;
import nutricionista.accesodatos.DietaComidaData;
import nutricionista.accesodatos.DietaData;
import nutricionista.entidades.Comida;
import nutricionista.entidades.Dieta;
import nutricionista.entidades.DietaComida;
import nutricionista.entidades.Paciente;

/**
 *
 * @author Jorge Santiago
 */
public class ListaComidaDieta extends javax.swing.JInternalFrame {

    private Dieta dietaactual;
    private Comida comidaactual;
    private Paciente pacienteactual;
    private DietaData dietadata;
    private ComidaData comdata;
    private DietaComidaData dietacomidadata;
    private List <Comida> comidas;
    private List <Dieta> dietas; 
    private DefaultTableModel tabla= new DefaultTableModel();
    
    /**
     * Creates new form ListaComidaDieta
     */
    public ListaComidaDieta() {
        initComponents();
        
        comdata= new ComidaData();
        dietadata= new DietaData();
        dietacomidadata= new DietaComidaData();
        comidas=(ArrayList<Comida>)comdata.ListarComidas();
        dietas=(ArrayList<Dieta>)dietadata.ListaDieta();
        
        armarTabla();
        cargaDieta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRComidasEnDieta = new javax.swing.JRadioButton();
        jRComidasFueraDieta = new javax.swing.JRadioButton();
        jCDietas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaComidas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jBAgregar = new javax.swing.JButton();
        jBorrar = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Seleccione una Dieta");

        jRComidasEnDieta.setText("Comidas Incluidas en la Dieta");
        jRComidasEnDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRComidasEnDietaActionPerformed(evt);
            }
        });

        jRComidasFueraDieta.setText("Comidas No Incluidas en la Dieta");
        jRComidasFueraDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRComidasFueraDietaActionPerformed(evt);
            }
        });

        jCDietas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCDietasActionPerformed(evt);
            }
        });

        jTablaComidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablaComidas);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("LIsta de Comidas");

        jBAgregar.setText("Agregar");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jBorrar.setText("Borrar");
        jBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCDietas, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jRComidasEnDieta)
                        .addGap(18, 18, 18)
                        .addComponent(jRComidasFueraDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jBAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBorrar)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCDietas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRComidasEnDieta)
                    .addComponent(jRComidasFueraDieta))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregar)
                    .addComponent(jBorrar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRComidasFueraDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRComidasFueraDietaActionPerformed
         
        borrarFilasTablas();
        jRComidasEnDieta.setSelected(false);
        cargarComidasTodas();
        jBorrar.setEnabled(false);
        jBAgregar.setEnabled(true);
        
    }//GEN-LAST:event_jRComidasFueraDietaActionPerformed

    private void jRComidasEnDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRComidasEnDietaActionPerformed
       borrarFilasTablas();
       jRComidasFueraDieta.setSelected(false);
       cargarComidasIncluidas();
       jBorrar.setEnabled(true);
       jBAgregar.setEnabled(false);
    }//GEN-LAST:event_jRComidasEnDietaActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
       int filasSelec= jTablaComidas.getSelectedRow();

        if (filasSelec!=-1){
            
            Dieta d= (Dieta)jCDietas.getSelectedItem();
            int id= (Integer)tabla.getValueAt(filasSelec, 0);
            String nombrecomida= (String)tabla.getValueAt(filasSelec, 1);
            String detallecomida=(String)tabla.getValueAt(filasSelec, 2);
            int caloriascomida= (Integer)tabla.getValueAt(filasSelec, 3);
            
            Comida c= new Comida(nombrecomida,detallecomida,caloriascomida);
            
            DietaComida dc= new DietaComida(c, d);
            
            dietacomidadata.GuardarDietaComida(dc);
            
            borrarFilasTablas();



        }
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBorrarActionPerformed
       
        int filasSelec= jTablaComidas.getSelectedRow();
        if (filasSelec!=-1){
            Dieta d= (Dieta)jCDietas.getSelectedItem();
 
            int id= (Integer)tabla.getValueAt(filasSelec, 0);
            
            dietacomidadata.borrarDietaComida(id, d.getId_dieta());
            
           
            borrarFilasTablas();
            
      
        }
    }//GEN-LAST:event_jBorrarActionPerformed

    private void jCDietasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCDietasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCDietasActionPerformed

    private void armarTabla(){
    ArrayList<Object> filaCabecera =new ArrayList<>();
    filaCabecera.add("ID");
    filaCabecera.add("NOMBRE");
    filaCabecera.add("DETALLE");
    filaCabecera.add("CALORIAS");
    
    for(Object it: filaCabecera){
    tabla.addColumn(it);   
}
    
   jTablaComidas.setModel(tabla);

}
    
   private void cargaDieta(){ //carga el combobox
    
    for(Dieta sel:dietas){
        
        jCDietas.addItem(sel);
        
    }
}    
    
   private void cargarComidasTodas(){
    
    
    List <Comida> comidas=(ArrayList) comdata.ListarComidas();
    for (Comida c: comidas){
      tabla.addRow(new Object[] { c.getId_comida(),c.getNombre(), c.getDetalle(),c.getCantCalorias() });
    }
}
   
    private void cargarComidasIncluidas(){
    
    Dieta selec= (Dieta)jCDietas.getSelectedItem();
    List <Comida> comidas=(ArrayList) dietacomidadata.ListarComidasIncluidas(selec.getId_dieta());
    for (Comida c: comidas){
      tabla.addRow(new Object[] { c.getId_comida(), c.getNombre(), c.getDetalle(),c.getCantCalorias() });
    }
}
    
    private void borrarFilasTablas(){
    int indice=tabla.getRowCount()-1;
    for (int i =indice ;i>=0;i--){
        tabla.removeRow(i);
    }
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBorrar;
    private javax.swing.JComboBox<Dieta> jCDietas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRComidasEnDieta;
    private javax.swing.JRadioButton jRComidasFueraDieta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaComidas;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
